/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PressDossierRouteImport } from './routes/press-dossier'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as WorksRouteImport } from './routes/works'
import { Route as CategoryIndexRouteImport } from './routes/$category.index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as MediaTypeRouteImport } from './routes/media.$type'
import { Route as CategoryWorkIndexRouteImport } from './routes/$category.$work.index'
import { Route as CategoryWorkPieceRouteImport } from './routes/$category.$work.$piece'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBiographyRouteImport } from './routes/_authenticated/admin.biography'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminMediaSeoRouteImport } from './routes/_authenticated/admin.media-seo'
import { Route as AuthenticatedAdminMediaSlotsRouteImport } from './routes/_authenticated/admin.media-slots'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminPublicationsRouteImport } from './routes/_authenticated/admin.publications'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSubcategoriesRouteImport } from './routes/_authenticated/admin.subcategories'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminWorksRouteImport } from './routes/_authenticated/admin.works'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PressDossierRoute = PressDossierRouteImport.update({
  id: '/press-dossier',
  path: '/press-dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoryRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaTypeRoute = MediaTypeRouteImport.update({
  id: '/media/$type',
  path: '/media/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryWorkIndexRoute = CategoryWorkIndexRouteImport.update({
  id: '/$work/',
  path: '/$work/',
  getParentRoute: () => CategoryRoute,
} as any)
const CategoryWorkPieceRoute = CategoryWorkPieceRouteImport.update({
  id: '/$work/$piece',
  path: '/$work/$piece',
  getParentRoute: () => CategoryRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBiographyRoute =
  AuthenticatedAdminBiographyRouteImport.update({
    id: '/biography',
    path: '/biography',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMediaSeoRoute =
  AuthenticatedAdminMediaSeoRouteImport.update({
    id: '/media-seo',
    path: '/media-seo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaSlotsRoute =
  AuthenticatedAdminMediaSlotsRouteImport.update({
    id: '/media-slots',
    path: '/media-slots',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPublicationsRoute =
  AuthenticatedAdminPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubcategoriesRoute =
  AuthenticatedAdminSubcategoriesRouteImport.update({
    id: '/subcategories',
    path: '/subcategories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWorksRoute = AuthenticatedAdminWorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$category': typeof CategoryRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/press-dossier': typeof PressDossierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/works': typeof WorksRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/media/$type': typeof MediaTypeRoute
  '/$category/': typeof CategoryIndexRoute
  '/media/': typeof MediaIndexRoute
  '/$category/$work/$piece': typeof CategoryWorkPieceRoute
  '/admin/biography': typeof AuthenticatedAdminBiographyRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/media-seo': typeof AuthenticatedAdminMediaSeoRoute
  '/admin/media-slots': typeof AuthenticatedAdminMediaSlotsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/publications': typeof AuthenticatedAdminPublicationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subcategories': typeof AuthenticatedAdminSubcategoriesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/works': typeof AuthenticatedAdminWorksRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$category/$work/': typeof CategoryWorkIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/press-dossier': typeof PressDossierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/works': typeof WorksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/media/$type': typeof MediaTypeRoute
  '/$category': typeof CategoryIndexRoute
  '/media': typeof MediaIndexRoute
  '/$category/$work/$piece': typeof CategoryWorkPieceRoute
  '/admin/biography': typeof AuthenticatedAdminBiographyRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/media-seo': typeof AuthenticatedAdminMediaSeoRoute
  '/admin/media-slots': typeof AuthenticatedAdminMediaSlotsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/publications': typeof AuthenticatedAdminPublicationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subcategories': typeof AuthenticatedAdminSubcategoriesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/works': typeof AuthenticatedAdminWorksRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$category/$work': typeof CategoryWorkIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$category': typeof CategoryRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/press-dossier': typeof PressDossierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/works': typeof WorksRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/media/$type': typeof MediaTypeRoute
  '/$category/': typeof CategoryIndexRoute
  '/media/': typeof MediaIndexRoute
  '/$category/$work/$piece': typeof CategoryWorkPieceRoute
  '/_authenticated/admin/biography': typeof AuthenticatedAdminBiographyRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/media-seo': typeof AuthenticatedAdminMediaSeoRoute
  '/_authenticated/admin/media-slots': typeof AuthenticatedAdminMediaSlotsRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/publications': typeof AuthenticatedAdminPublicationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subcategories': typeof AuthenticatedAdminSubcategoriesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/works': typeof AuthenticatedAdminWorksRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/$category/$work/': typeof CategoryWorkIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$category'
    | '/architecture'
    | '/auth'
    | '/contact'
    | '/news'
    | '/press-dossier'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/works'
    | '/admin'
    | '/email/unsubscribe'
    | '/media/$type'
    | '/$category/'
    | '/media/'
    | '/$category/$work/$piece'
    | '/admin/biography'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/media'
    | '/admin/media-seo'
    | '/admin/media-slots'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/publications'
    | '/admin/settings'
    | '/admin/subcategories'
    | '/admin/users'
    | '/admin/works'
    | '/lovable/email/suppression'
    | '/$category/$work/'
    | '/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/architecture'
    | '/auth'
    | '/contact'
    | '/news'
    | '/press-dossier'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/works'
    | '/email/unsubscribe'
    | '/media/$type'
    | '/$category'
    | '/media'
    | '/$category/$work/$piece'
    | '/admin/biography'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/media'
    | '/admin/media-seo'
    | '/admin/media-slots'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/publications'
    | '/admin/settings'
    | '/admin/subcategories'
    | '/admin/users'
    | '/admin/works'
    | '/lovable/email/suppression'
    | '/$category/$work'
    | '/admin'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/$category'
    | '/architecture'
    | '/auth'
    | '/contact'
    | '/news'
    | '/press-dossier'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/works'
    | '/_authenticated/admin'
    | '/email/unsubscribe'
    | '/media/$type'
    | '/$category/'
    | '/media/'
    | '/$category/$work/$piece'
    | '/_authenticated/admin/biography'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/media-seo'
    | '/_authenticated/admin/media-slots'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/publications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subcategories'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/works'
    | '/lovable/email/suppression'
    | '/$category/$work/'
    | '/_authenticated/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  PressDossierRoute: typeof PressDossierRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WorksRoute: typeof WorksRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  MediaTypeRoute: typeof MediaTypeRoute
  MediaIndexRoute: typeof MediaIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-dossier': {
      id: '/press-dossier'
      path: '/press-dossier'
      fullPath: '/press-dossier'
      preLoaderRoute: typeof PressDossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$type': {
      id: '/media/$type'
      path: '/media/$type'
      fullPath: '/media/$type'
      preLoaderRoute: typeof MediaTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$work/': {
      id: '/$category/$work/'
      path: '/$work'
      fullPath: '/$category/$work/'
      preLoaderRoute: typeof CategoryWorkIndexRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/$category/$work/$piece': {
      id: '/$category/$work/$piece'
      path: '/$work/$piece'
      fullPath: '/$category/$work/$piece'
      preLoaderRoute: typeof CategoryWorkPieceRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/biography': {
      id: '/_authenticated/admin/biography'
      path: '/biography'
      fullPath: '/admin/biography'
      preLoaderRoute: typeof AuthenticatedAdminBiographyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media-seo': {
      id: '/_authenticated/admin/media-seo'
      path: '/media-seo'
      fullPath: '/admin/media-seo'
      preLoaderRoute: typeof AuthenticatedAdminMediaSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media-slots': {
      id: '/_authenticated/admin/media-slots'
      path: '/media-slots'
      fullPath: '/admin/media-slots'
      preLoaderRoute: typeof AuthenticatedAdminMediaSlotsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/publications': {
      id: '/_authenticated/admin/publications'
      path: '/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AuthenticatedAdminPublicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subcategories': {
      id: '/_authenticated/admin/subcategories'
      path: '/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AuthenticatedAdminSubcategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/works': {
      id: '/_authenticated/admin/works'
      path: '/works'
      fullPath: '/admin/works'
      preLoaderRoute: typeof AuthenticatedAdminWorksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBiographyRoute: typeof AuthenticatedAdminBiographyRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMediaSeoRoute: typeof AuthenticatedAdminMediaSeoRoute
  AuthenticatedAdminMediaSlotsRoute: typeof AuthenticatedAdminMediaSlotsRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminPublicationsRoute: typeof AuthenticatedAdminPublicationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubcategoriesRoute: typeof AuthenticatedAdminSubcategoriesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorksRoute: typeof AuthenticatedAdminWorksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBiographyRoute: AuthenticatedAdminBiographyRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMediaSeoRoute: AuthenticatedAdminMediaSeoRoute,
  AuthenticatedAdminMediaSlotsRoute: AuthenticatedAdminMediaSlotsRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminPublicationsRoute: AuthenticatedAdminPublicationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubcategoriesRoute: AuthenticatedAdminSubcategoriesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorksRoute: AuthenticatedAdminWorksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CategoryRouteChildren {
  CategoryIndexRoute: typeof CategoryIndexRoute
  CategoryWorkPieceRoute: typeof CategoryWorkPieceRoute
  CategoryWorkIndexRoute: typeof CategoryWorkIndexRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryIndexRoute: CategoryIndexRoute,
  CategoryWorkPieceRoute: CategoryWorkPieceRoute,
  CategoryWorkIndexRoute: CategoryWorkIndexRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  CategoryRoute: CategoryRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  PressDossierRoute: PressDossierRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WorksRoute: WorksRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  MediaTypeRoute: MediaTypeRoute,
  MediaIndexRoute: MediaIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
